version: '3.7'

services:
  web:
    build: .
#    working_dir: /opt/www
    restart: always
#    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "app.service:app"]
    volumes:
      - ./app/:/app/app/
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: "1"
