version: '3.7'

services:
  covid19-landing:
    build: .
    restart: always
#    volumes:
#      - ./app/:/app/app/
#      - ./server/supervisord.conf:/opt/supervisor/supervisord.conf
#      - ./server/gunicorn_conf.py:/gunicorn_conf.py
#      - ./app/static/dist/application.css:/app/static/application.css
#      - ./app/static/images:/app/static/images
#      - ./app/static/govuk-frontend:/app/static/govuk-frontend
#      - ./server/upload.nginx:/etc/nginx/conf.d/upload.conf
#      - ./server/engine.nginx:/etc/nginx/conf.d/engine.conf
    ports:
      - 5100:5100
    env_file:
      - .env.dev
    environment:
      IS_DEV: 1
      API_ENV: DEVELOPMENT
