version: '3.7'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./app/:/app/app/
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: 0
      API_ENV: PRODUCTION
      FLASK_ENV: PRODUCTION
