version: '3.7'

services:
  covid19-landing:
    build: .
    restart: always
    volumes:
      - ./app:/opt/app
      - ./app/assets/css:/opt/assets
    ports:
      - 5100:5100
    env_file:
      - .env.dev
    environment:
      IS_DEV: 0
      API_ENV: DEVELOPMENT
