version: '3.7'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./app/:/app/app/
      - ./server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./server/gunicorn_conf.py:/gunicorn_conf.py
      - ./app/static/dist/application.css:/app/static/application.css
      - ./app/static/images:/app/static/images
      - ./app/static/govuk-frontend:/app/static/govuk-frontend
      - ./server/upload.nginx:/etc/nginx/conf.d/upload.conf
      - ./server/engine.nginx:/etc/nginx/conf.d/engine.conf
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: 1
      API_ENV: DEVELOPMENT
      FLASK_ENV: DEVELOPMENT
